### ISSUE TITLE
add last quote bug

### ISSUE THREAD

**Issue by mayim-chayim** [mordechairoth/IveltChromeExtension#31]
add last quote fails if there is a quote without a username 
see [here](http://www.ivelt.com/forum/viewtopic.php?f=21&t=48&start=950#p2867601) for an example

**Comment by mordechairoth** [comment]
@mayim-chayim will you fix the bug? (I already want to publish the updated version, but if you plan to fix this I want to wait until you fix it)

**Comment by mayim-chayim** [comment]
> @mayim-chayim will you fix the bug? (I already want to publish the updated version, but if you plan to fix this I want to wait until you fix it)

probably not in the immediate future maybe later 
please publish the updates

**Comment by KFMDMSolutions** [comment]
btw
with @bevekashaivelt code it should be fixed
see [here](https://www.ivelt.com/forum/viewtopic.php?p=3374849#p3374849)
