### ISSUE TITLE
Extension Auto Publish

### ISSUE THREAD

**Issue by kavhayushar** [mordechairoth/IveltChromeExtension#32]
Would be a good idea to set up an Action to Auto Publish the extension on every new Tag Release.
See [here](https://github.com/marketplace/actions/chrome-extension-upload-action) a ready action for this. (If I'm not wrong, Actions is free for public repos)

What do y'all think about this?

**Comment by mordechairoth** [comment]
I actually would like to not have auto publish, at least for now, so that I should be able to review everything and check for bugs before publishing.

**Comment by kavhayushar** [comment]
Understood.
Just trying to make life easier...
If/When ready to reconsider, there is an option to require at least two approvals before merging. Having such requirement will give us another layer of security and prevent bugs from slipping through.

I'm thinking now that you can still benefit from this by having a designated branch (prod) where only you have merging access and whenever and setup auto build from that branch. All you'll need to do is merging from Master to that specific branch. Will save you a lot of time.
