### ISSUE TITLE
Browser notifications

### ISSUE THREAD

**Issue by nefshech** [mordechairoth/IveltChromeExtension#41]
Send a browser notification when the user's profile receives a notification.

Discussion: https://www.ivelt.com/forum/viewtopic.php?f=2&t=50384

**Comment by bevekashaivelt** [comment]
You might want to check out the code of the android app

 https://github.com/KFMDMSolutions/Ivelt-Android-App/blob/main/app/src/main/java/com/kfmdmsolutions/ivelt/NotificationService.java

start from line 156

**Comment by nefshech** [comment]
Concept: Create a fragment from the response from http://www.ivelt.com/forum/ucp.php?i=ucp_notifications and then loop through all elements and send a notification for each one.

Then somehow save to storage that this was already sent.

Is this the best approach?

**Comment by mayim-chayim** [comment]
> Can anybody explain what is the purpose of [js/refreshNotificationCount.js](https://github.com/mordechairoth/IveltChromeExtension/blob/master/extension/js/refreshNotificationCount.js)?

to update the count instantly when changes are made if possible, e.g. when a notification is checked

**Comment by nefshech** [comment]
> > > to update the count instantly when changes are made if possible, e.g. when a notification is checked
> > 
> > 
> > It only observes the `notification_list_button` which, to my understanding, is not being updated while on the page. No?
> 
> it is, when you check a notification ![image](https://user-images.githubusercontent.com/85243488/136860615-558bd42f-5c26-4fd7-9df4-f7de1a50093f.png)

Why could it not wait for the alarm, they wanted it to be immediately updated? It really seems like duplicate code.

The reason I'm asking, in order to work on browser notifications there needs to be one streamlined way of getting new notifications and then work with it.

**Comment by nefshech** [comment]
> why not just use the alarm and ignore the other file?

That's probably what will end up being done, but setting the badge when marked as read should be done via a message and not fetch the notifications itself to avoid fetching in 2 places.

The question remains if background.js supports fragments and element filtering to filter through the loaded notifications, if not, everything will need to be done in content scripts.

**Comment by nefshech** [comment]
Reloaded multiple times, ```chrome.notifications``` was undefined until reinstalling the unpacked extension.

**Comment by KnaperYaden** [comment]
@nefshech I installed from https://github.com/nefshech/IveltChromeExtension/tree/browser-notifications and I do not get the OS notifications at all.

I have it installed both in (Chromium) Edge and in Chrome.

Tried manually setting notification setting from ivelt to Allow, but didn't help.

Anything else to check/try?

**Comment by nefshech** [comment]
@KnaperYaden it's OFF by default, did you turn it on in extension settings?

**Comment by KnaperYaden** [comment]
> @KnaperYaden it's OFF by default, did you turn it on in extension settings?

Yeah, of course.

**Comment by nefshech** [comment]
Hmm.. probably not the case, but it only works on https.

What else, any errors in the console?chrome.runtime.lastError contains anything?

Open the browser console for the extension from the chrome://extensions page by clicking on the "service worker" link.

**Comment by KnaperYaden** [comment]
> What else, any errors in the console?chrome.runtime.lastError contains anything?
> 
> Open the browser console for the extension from the chrome://extensions page by clicking on the "service worker" link.

- I opened the service worker dev tools (in Edge) and got a notification (through Edge) a sec later!
- I then closed the Edge dev tools, and opened the service worker dev tools in Chrome, and before you know it I'm getting a Chrome notification
- Closed both and got neither of them (to note, while no notification the extension badge count moves up)
- Opened both and got from both

Maybe because I have Disabled Cache checked in Dev Tools and the issue I have is something with Cache?

**Comment by nefshech** [comment]
Before clicking on the service worker link, did it by chance say "service worker (inactive)"?

I had this situation randomly that I didn't get notifications and somehow related it to the inactive note. Seems like the extension background script is going to sleep while not in use. Not sure how this can be fixed because the badge is working as expected.

**Comment by KnaperYaden** [comment]
> Before clicking on the service worker link, did it by chance say "service worker (inactive)"?
> 
> I had this situation randomly that I didn't get notifications and somehow related it to the inactive note. Seems like the extension background script is going to sleep while not in use. Not sure how this can be fixed because the badge is working as expected.

It sometimes said Inactive, but other times not.

I think this is automatically awaken when the check for new notifications occurs, which is expected and not an issue.

In fact I kept on refreshing the page and saw if coming in and going out from Inactive.

**Comment by nefshech** [comment]
I figured it's expected to wake up when needed (onmessage or onalert events) and that's what makes me wonder why the notifications are not coming in when inactive.

Note: when devtools is opened, the service worker (background script) is automatically awakened to serve the devtools context (and that's probably why you got the notifications at that moment)
