### ISSUE TITLE
Rename repository to iVelt Helper

### ISSUE THREAD

**Issue by Sunegi** [mordechairoth/IveltChromeExtension#46]
Extension is not exclusive to Chrome, can run in Edge too.

**Comment by mordechairoth** [comment]
(exclusive to chromium)

**Comment by mordechairoth** [comment]
The extension is being built for the Chrome store.
Also @Sunegi  are you sure that renaming the repo doesn't have any side effects?

**Comment by Sunegi** [comment]
Checked. None that affect this project.

**Comment by Sunegi** [comment]
Bump.

**Comment by Sunegi** [comment]
Bump.

**Comment by mordechairoth** [comment]
Closing this issue, because it does not effect the functionality of the extension or the DX.
