### ISSUE TITLE
Migrate to MV3

### ISSUE THREAD

**Issue by mordechairoth** [mordechairoth/IveltChromeExtension#49]
https://developer.chrome.com/docs/extensions/mv3/intro/mv3-migration/
This will help extension updates get approved faster by Google.

**Comment by nefshech** [comment]
Per https://developer.chrome.com/blog/mv2-transition

> **January 2023**: The Chrome browser will no longer run Manifest V2 extensions. Developers may no longer push updates to existing Manifest V2 extensions.

**Comment by nefshech** [comment]
If anyone is working on this please comment.

**Comment by chucem** [comment]
WIP https://github.com/chucem/IveltChromeExtension/tree/update_to_MV3

**Comment by chucem** [comment]
can be closed?

**Comment by kavhayushar** [comment]
Has already been resolved. Thanks @chucem
