### ISSUE TITLE
Browser Notifications Not Working

### ISSUE THREAD

**Issue by KnaperYaden** [mordechairoth/IveltChromeExtension#50]
As we started to discuses in #41, as well as discussions https://www.ivelt.com/forum/viewtopic.php?p=3113317#p3113317, the browser notifications doesn't seem to work for most users.

As we found, when Dev Tools it open it does work.

What's the next step?

**Comment by nefshech** [comment]
Working on a fix.

**Comment by nefshech** [comment]
Want to add a debugging mode which would save logs in storage and can be helpful to debug issues on various OS/devices, specifically notifications.

Adding a "Debug mode" checkbox option in settings doesn't seem to be a good choice to me. @Sunegi what do you think?

**Comment by KnaperYaden** [comment]
Why is a debug check box not a good choice (not same as the other options checkboxes, but in the side small)?

You can at least tell me how to add debugging to mine locally... I'll send you the logs.

**Comment by nefshech** [comment]
Please see the PR for a debug mode. The UI for this option can be improved, please share your ideas.

**Comment by KnaperYaden** [comment]
> Please see the PR for a debug mode. The UI for this option can be improved, please share your ideas.

👍

Installed now, I'll test and come back with how it is.

**Comment by nefshech** [comment]
> > Please see the PR for a debug mode. The UI for this option can be improved, please share your ideas.
> 
> 👍
> 
> Installed now, I'll test and come back with how it is.

Any issues so far? Is it working now?

**Comment by KnaperYaden** [comment]
@nefshech so far so good with this version with the notifications.
