### ISSUE TITLE
Related Topics

### ISSUE THREAD

**Issue by bevekashaivelt** [mordechairoth/IveltChromeExtension#9]
I want to implement a similar threads button. The question is how do we know which thread are related? 

I am thinking that maybe we add a custom tag called related, is that a good idea? 
If I were to make a pull request with such an implementation, would it be accepted?
Is there maybe a better idea on how to find related topics?

Should I open a thread on Ivelt about it?

**Comment by ShimonLeb** [comment]
> The question is how do we know which thread are related?

I don't think it is possible, the best way to get related threads is by asking @Knaper

> Should I open a thread on Ivelt about it?

post the question on the existing thread
http://www.ivelt.com/forum/viewtopic.php?f=2&t=46302&start=100

**Comment by YisroelTech** [comment]
IMHO this is beyond the scope (sorta the like option...) it would need some back-end to store the info, and it's going to cause a strange experience when some people have it and some don't have it.

I think the focus with this should be more on added utility to what currently exists.

About PRs here. Not sure @mordechairoth is interested in actively managing a project with PRs from others. Perhaps (with his permission) @kavhayushar or @bevekashaivelt (both of whom I think are way more actively involved on ivelt) should fork it.

**Comment by bevekashaivelt** [comment]
It can be done without a backend, but wouldn't be 100% reliable, as it would rely on ivelt's search. Regarding forking, forking in of itself will not help, because you still need to push to the Chrome Extension Store, which would require @mordechairoth's credentials.

**Comment by YisroelTech** [comment]
Meant to say forking and publishing anew.

**Comment by mordechairoth** [comment]
@bevekashaivelt I want this extension to be only for accessibly features, and things that make it easier to use the site, I understand that a related will make it more fun, but I wouldn't consider that accessibly.
Also if the entire thing is implemented in the frontend I think that it might cause the page to slow down and it may not even be efficient as you mentioned.
Also, I want to keep this for features that will not really change the experience for the user and only add minimal  amount of UI elements.

**Comment by bevekashaivelt** [comment]
OK np, glad I asked before doing all the work.
